### PR TITLE
Add reference to alertmanager

### PR DESCRIPTION
**Pull request by mrunge**
... to route notifications and alerts to alertmanager.

### CODE REVIEW

**Comment by leifmadsen** [comment]
Can you elaborate on what this patch provides functionally, along with some testing output?

**Comment by mrunge** [comment]
Without this patch, prometheus des not know where to push events to. With this patch, you'll get outputs like these in alertmanager: https://github.com/mrunge/saf-documentation/blob/promrules/doc-Service-Assurance-Framework/modules/alertmanager_alerts-overview.png

After using a secret like this
```
kind: Secret
metadata:
  name: alertmanager-saf-default
  namespace: sa-telemetry
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 31s
      group_interval: 4m
      repeat_interval: 12h
      receiver: 'webhook'

      routes:
      - match:
          severity: critical
        receiver: 'webhook-crit'
      - match_re:
          severity: !(critical)
        receiver: 'webhook'
    templates:
    - '*.tmpl'
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: http://192.168.36.9/webhook
    - name: 'webhook-crit'
      webhook_configs:
      - url: http://192.168.36.9/webhook-crit

```
I am able to get alerts:
```
[root@wandboard httpd]# tail -f access_log
192.168.36.10 - - [27/Jan/2020:13:35:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:13:39:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:13:43:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:13:47:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:13:51:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:13:55:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:13:59:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:03:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:07:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:16:36 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:17:45 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:18:31 +0100] "POST /webhook HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:18:31 +0100] "POST /webhook-crit HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
192.168.36.10 - - [27/Jan/2020:14:19:36 +0100] "POST /webhook-crit HTTP/1.1" 404 196 "-" "Alertmanager/0.17.0"
```

**Comment by mrunge** [comment]
yes, it's just the pointer to alertmanager. It is not perfect yet, the pointer back from alertmanager to prometheus in alertmanager points to prometheus' short name, e.g `http://prometheus-saf-default-0:9090/graph?g0.expr=vector%281%29&g0.tab=1`. That is not solved yet, I assume it is a matter of labeling and also a prometheus issue.

**Comment by csibbitt** [comment]
> yes, it's just the pointer to alertmanager. It is not perfect yet, the pointer back from alertmanager to prometheus in alertmanager points to prometheus' short name, e.g `http://prometheus-saf-default-0:9090/graph?g0.expr=vector%281%29&g0.tab=1`. That is not solved yet, I assume it is a matter of labeling and also a prometheus issue.

Is this link back to prometheus required for important alertmanager functionality, or a feature of the web UI for the user only? The links to prometheus are never going to work for the user unless we enable the route that exposes prometheus outside the cluster, which we've deliberately avoided so far.

**Comment by mrunge** [comment]
Thank you.

The link back to prometheus is a minor imho in the alertmanager UI. It shows, when you click on source in https://github.com/mrunge/saf-documentation/blob/promrules/doc-Service-Assurance-Framework/modules/alertmanager_alerts-overview.png for each alert.

**Pull request merged**
