### PR TITLE
QDR HA

### PR DESCRIPTION
**Pull request by csibbitt**
* I'm trying to dovetail with the operator API work here instead of
reproducing it: https://github.com/redhat-service-assurance/service-assurance-operator/pull/23/
* Should be safe to merge even ahead of that work

### CODE REVIEW

**Comment by csibbitt** [comment]
[Adjust server side automation for HA QDR](https://trello.com/c/DsSsOkUq/785-adjust-server-side-automation-for-ha-qdr)

**Comment by csibbitt** [comment]
## Testing

## Start with a build of this branch running one QDR

```
$ oc describe pod -l name=service-assurance-operator | grep "Image ID"
    Image ID:      image-registry.openshift-image-registry.svc:5000/sa-telemetry/service-assurance-operator@sha256:09ebff5f49f02841abed28ef9701601a76249929d016149f7c5bf04aec5e433c


$ oc get po | egrep 'default-interconnect'
saf-default-interconnect-664bc78f79-64qr8        1/1     Running            0          35m
```
sha256:09ebff

## Push a new build with HA on by default

```
[csibbitt@laptop service-assurance-operator (csibbitt-785-ha-qdr) (⎈ |sa-telemetry/api-crc-testing:6443/system:admin)]$ git diff
diff --git a/roles/serviceassurance/defaults/main.yml b/roles/serviceassurance/defaults/main.yml
index 88a3584..6355628 100644
--- a/roles/serviceassurance/defaults/main.yml
+++ b/roles/serviceassurance/defaults/main.yml
@@ -2,7 +2,7 @@
 # set default enablement
 metrics_enabled: true
 events_enabled: false
-high_availability_enabled: false
+high_availability_enabled: true

[csibbitt@laptop service-assurance-operator (csibbitt-785-ha-qdr) (⎈ |sa-telemetry/api-crc-testing:6443/system:admin)]$ operator-sdk build "${REGISTRY}/sa-telemetry/service-assurance-operator"
INFO[0000] Building OCI image default-route-openshift-image-registry.apps-crc.testing/sa-telemetry/service-assurance-operator 
Sending build context to Docker daemon  347.6kB
Step 1/3 : FROM quay.io/operator-framework/ansible-operator:v0.12.0
 ---> e5e4e696bab8
Step 2/3 : COPY watches.yaml ${HOME}/watches.yaml
 ---> Using cache
 ---> f8f8885a5533
Step 3/3 : COPY roles/ ${HOME}/roles/
 ---> af1bbc6ef7fd
Successfully built af1bbc6ef7fd
Successfully tagged default-route-openshift-image-registry.apps-crc.testing/sa-telemetry/service-assurance-operator:latest
INFO[0000] Operator build complete.     
               
[csibbitt@laptop service-assurance-operator (csibbitt-785-ha-qdr) (⎈ |sa-telemetry/api-crc-testing:6443/system:admin)]$ docker push default-route-openshift-image-registry.apps-crc.testing/sa-telemetry/service-assurance-operator
The push refers to repository [default-route-openshift-image-registry.apps-crc.testing/sa-telemetry/service-assurance-operator]
396b9ec7261c: Pushed 
5c78987c1295: Layer already exists 
964b072de0ec: Layer already exists 
34eed33aab83: Layer already exists 
bdf14bfd44c7: Layer already exists 
9f1d59d4b67c: Layer already exists 
2518edbbf131: Layer already exists 
c545c8a3743d: Layer already exists 
a08696fdf18d: Layer already exists 
02675fc38de1: Layer already exists 
62698a65468c: Layer already exists 
48905dae4010: Layer already exists 
6866631b657e: Layer already exists 
latest: digest: sha256:36f9416d8ed00c07b597731653baf0ba962359f5fc6cc938787cc996d9287c5b size: 3028
```
sha256:36f941

## Trigger an update of the SAO pod

```
$ oc delete po -l name=service-assurance-operator
pod "service-assurance-operator-bcbf9c9fd-p7tc5" deleted

$ oc get po -l name=service-assurance-operator 
NAME                                         READY   STATUS    RESTARTS   AGE
service-assurance-operator-bcbf9c9fd-f9bjd   2/2     Running   0          66s

$ oc describe pod -l name=service-assurance-operator | grep "Image ID"
    Image ID:      image-registry.openshift-image-registry.svc:5000/sa-telemetry/service-assurance-operator@sha256:36f9416d8ed00c07b597731653baf0ba962359f5fc6cc938787cc996d9287c5b
    Image ID:       image-registry.openshift-image-registry.svc:5000/sa-telemetry/service-assurance-operator@sha256:36f9416d8ed00c07b597731653baf0ba962359f5fc6cc938787cc996d9287c5b

```
sha256:36f941

## Check that there are now two QDRs

```
$ oc get po | egrep 'default-interconnect'
saf-default-interconnect-664bc78f79-5hh2x        1/1     Running            0          3m32s
saf-default-interconnect-664bc78f79-64qr8        1/1     Running            0          72m
```

**Comment by elfiesmelfie** [comment]
I've updated #23, so the formatting/ordering matches, so there should be less issue merging it all in later

**Comment by csibbitt** [comment]
@elfiesmelfie gave me her +1 OOB. Going to merge this now and it should become more usable when https://github.com/redhat-service-assurance/service-assurance-operator/pull/23 merges too.

**Pull request merged**
